"""Virtual RAPPID Debug Card contract and deterministic simulator."""

from .artifacts import write_rappid_card_fixture_deck
from .contract import (
    CARD_CHALLENGE_DOMAIN,
    CARD_SIGNATURE_DOMAIN,
    canonical_manifest,
    challenge_value,
    classification_rank,
    compare_semver,
    make_deep_link,
    manifest_hash,
    parse_deep_link,
    parse_manifest_json,
    sign_manifest,
    signature_value,
    unsigned_manifest,
    validate_manifest,
    verify_challenge,
    verify_signature,
)
from .fixtures import (
    FIXTURE_CHALLENGE_KEY_ID,
    FIXTURE_ENDPOINT,
    FIXTURE_SIGNING_KEY_ID,
    RAPPID_CARD_FIXTURE_NAMES,
    RAPPID_CARD_FIXTURE_NOW,
    RappidCardFixture,
    build_rappid_card_fixture,
    build_rappid_card_vector_document,
    list_rappid_card_fixtures,
    simulate_rappid_card_fixture,
)
from .qr import render_rappid_card_qr_png, render_rappid_card_qr_svg
from .replay_cache import BoundedReplayCache
from .simulator import (
    initial_card_snapshot,
    reduce_card_state,
    simulate_rappid_card,
)
from .types import (
    MAX_AUDIT_EVENTS,
    MAX_REPLAY_NONCES,
    RAPPID_CARD_FILENAME,
    RAPPID_CARD_PRODUCTION_PROFILE,
    RAPPID_CARD_PROTOCOL,
    RAPPID_CARD_SCHEMA,
    RAPPID_CARD_TEST_PROFILE,
    CardPolicy,
    CardProviders,
    RappidCardError,
    RappidCardReconnectError,
)

__all__ = [
    "CARD_CHALLENGE_DOMAIN",
    "CARD_SIGNATURE_DOMAIN",
    "FIXTURE_CHALLENGE_KEY_ID",
    "FIXTURE_ENDPOINT",
    "FIXTURE_SIGNING_KEY_ID",
    "MAX_AUDIT_EVENTS",
    "MAX_REPLAY_NONCES",
    "RAPPID_CARD_FILENAME",
    "RAPPID_CARD_FIXTURE_NAMES",
    "RAPPID_CARD_FIXTURE_NOW",
    "RAPPID_CARD_PRODUCTION_PROFILE",
    "RAPPID_CARD_PROTOCOL",
    "RAPPID_CARD_SCHEMA",
    "RAPPID_CARD_TEST_PROFILE",
    "BoundedReplayCache",
    "CardPolicy",
    "CardProviders",
    "RappidCardError",
    "RappidCardFixture",
    "RappidCardReconnectError",
    "build_rappid_card_fixture",
    "build_rappid_card_vector_document",
    "canonical_manifest",
    "challenge_value",
    "classification_rank",
    "compare_semver",
    "initial_card_snapshot",
    "list_rappid_card_fixtures",
    "make_deep_link",
    "manifest_hash",
    "parse_deep_link",
    "parse_manifest_json",
    "reduce_card_state",
    "render_rappid_card_qr_png",
    "render_rappid_card_qr_svg",
    "sign_manifest",
    "signature_value",
    "simulate_rappid_card",
    "simulate_rappid_card_fixture",
    "unsigned_manifest",
    "validate_manifest",
    "verify_challenge",
    "verify_signature",
    "write_rappid_card_fixture_deck",
]
